# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Production context
[context.production]
  command = "npm run build"

# Deploy preview context
[context.deploy-preview]
  command = "npm run build"

# Headers for caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://ui-avatars.com https://*.unsplash.com https://*.githubusercontent.com https://*.googleusercontent.com https://*.ytimg.com https://*.twimg.com https://*.cdninstagram.com https://*.medium.com https://*.amazonaws.com; connect-src 'self' https://*.supabase.co https://api.readability.com; font-src 'self' data: https://fonts.gstatic.com; media-src 'self' https://*.youtube.com https://*.vimeo.com"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"