# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist"
  ignore_warnings = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Preserve access to test pages
[[redirects]]
  from = "/test.html"
  to = "/test.html"
  status = 200

[[redirects]]
  from = "/minimal.html"
  to = "/minimal.html"
  status = 200

# Fallback for errors
[[redirects]]
  from = "/error"
  to = "/fallback.html"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/fallback.html"
  status = 404
  force = false

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_NAME = "ReadLtr"
  VITE_API_URL = "https://preeminent-truffle-338deb.netlify.app/api"
  VITE_MINIMAL_MODE = "false"
  # Note: Sensitive environment variables like SUPABASE_URL, SUPABASE_ANON_KEY, DATABASE_URL, and JWT_SECRET
  # should be set in the Netlify UI under Site settings > Build & deploy > Environment

# Production context
[context.production]
  command = "npm run build"

# Deploy preview context
[context.deploy-preview]
  command = "npm run build"

# Headers for caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://api.readability.com https://*.netlify.app wss://*.supabase.co; font-src 'self' data: https://fonts.gstatic.com; media-src 'self' https://*.youtube.com https://*.vimeo.com; worker-src 'self' blob:; block-all-mixed-content; frame-ancestors 'none'; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval'; script-src-attr 'self' 'unsafe-inline'; object-src 'none'"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"